### ISSUE TITLE
Unclosed RandomAccessFile and FileChannel

### ISSUE THREAD

**Issue by irvingans** [apache/jena#1846] opened 2023-04-17 07:29 UTC
### Version

3.16.0

### What happened?

This is similar to https://github.com/apache/jena/issues/1840, which I found in 
https://github.com/apache/jena/blob/main/jena-tdb1/src/main/java/org/apache/jena/tdb/base/file/ChannelManager.java. Here in the source code of ChannelManager, where RandomAccessFile and FileChannel are not closed properly in this class itself or any other caller classes. This could potentially lead to memory leaks and other issues.
![image](https://user-images.githubusercontent.com/70804456/232414045-507a45f3-1f1a-44da-ab4a-ba8eb7532383.png).

### Are you interested in making a pull request?

None

**Comment by afs** [comment] 2023-04-17 13:22
This is not a bug.

Here, the resource is returned from the function.
"return channel" passes out the file channel which has the random access file.

The IDE/compiler does not track that FileChannel has a handle on RandomAccesFile which is why there is `@SuppressWarnings("resource")`.

Channels are closed by ChannelManager.release --- although Channels are long lived so in all likelihood, not closed except by JVM exit.

(NB Windows does not properly release memory mapped files anyway - long standing Java issue that is "won't fix" in OpenJDK)

Jena is currently 4.7.0

**Comment by irvingans** [comment] 2023-04-18 06:10
Regard one point in your reply as :
![image](https://user-images.githubusercontent.com/70804456/232652510-133de375-332c-413e-bad4-a05105ca9bc7.png)
As per my understanding, this release function can only closed channels that exist in the map name2channel.

![image](https://user-images.githubusercontent.com/70804456/232652459-55d18ca7-7ac8-4692-925a-34e0d28a9435.png)

In the initiation of name2channel , only journals files are tracked. So this means ChannelManager.release are not able to make sure all files are closed properly, right?
![image](https://user-images.githubusercontent.com/70804456/232666483-a66ab915-810e-411d-86c4-45b1a8e40fb3.png)

**Comment by afs** [comment] 2023-04-18 07:05
Look at `DatasetGraphTDB.close()`. Datastructures have a close operation that cascades down the close, not that it matters. Databases do not follow the file paradigm of open-action-close. That's a transaction on the database.

In TDB2, close is a no-op. Datasets are only closed in unusual conditions, not in normal use.
There is one database object per process that coordinates all access and it remains for the lifetime of the JVM.

Because of concurrent access and transactions, it is not reliable to synchronously close a database. There is code to eject a database from the process but as it's javadocs says "use with care"  which means tests mainly.

> This could potentially lead to memory leaks and other issues.

Have you seen any leaks? What other issues?

**Comment by irvingans** [comment] 2023-04-19 02:39
I understand your points. Now assuming I am in a low concurrency scenario, I need to close these db-related files in my caller process myself. 
![image](https://user-images.githubusercontent.com/70804456/232952383-9a48b701-c262-4ffb-8fcf-2f49e07b80d5.png)

Are there any external interface or methods provided by Jena for me to use? Thanks.

**Comment by rvesse** [comment] 2023-04-19 09:07
Could you elucidate your use case more clearly?  It's not clear that there is actually any real issue here other than some IDE/code-scanning tool gave you a warning about a resource leak which as others have already said is sometimes by design in libraries like Jena

TDB databases are typically used as long lived resources (since they are persistent databases) for the life of a process.  Opening and closing many of them within a single process usually only happens for unit testing purposes and suggests your use case may not align with the intended use cases of the TDB API.

Jena also provides short-lived fully in-memory databases that can be used as an alternative to TDB.  TDB itself even has a fully in-memory mode i.e. non-persistent database that could be used if persistence is not required.

One other possibility if the memory footprint of TDB is a concern is to spawn separate Fuseki processes that hosts the TDB database and communicate with it via HTTP.  You can then kill off the child process when the database is no longer needed

**Comment by afs** [comment] 2023-04-19 15:58
Yes, we need details of the usage.

Use TDB2.

TDB used memory mapped files. FIle memory costs are not part of the JVM. They are in the file system cache and the space used shrinks if the machine has other demands on RAM.

The size process will look large but it is virtual memory size, not real. Virtual memory includes the mapped files but that does not mean they are in RAM, only that it is in the address space.

TDB1 is the same except it has some temporary use of memory for transactions.

If you are seeing the JVM size increase, make sure you have not set the heap space too high.
 Java will typically grow heap space before a major GC hgappens. Check this by running visualvm and forcing a GC. The visualvm UI will show in-use space.

Are you using TDB from code or with Fuseki?

Upgrade to 4.7.0

**Comment by afs** [comment] 2023-04-28 10:06
@irvingans - without a use case, there doesn't seem to be anything else to answer here. JVM memory usage isn't related to files (unless you run on a 32 bit JVM).

**Comment by afs** [comment] 2023-06-29 08:08
I think we've answered this issue. If not, please do reopen it with additional information.

**Closed by afs** 2023-06-29 08:08 UTC
