### ISSUE TITLE
Fuseki server fails to start in Spring Boot 3.0.0 and newer 

### ISSUE THREAD

**Issue by benjaminaaron** [apache/jena#1794] opened 2023-03-11 19:58 UTC
### Version

4.7.0

### What happened?

In Spring Boot `2.7.9` it works. But for all versions `3.0.0`-`3.0.4` it fails with this error message:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at org.apache.jena.fuseki.main.FusekiServer.create(FusekiServer.java:137)
	at org.example.Application.main(Application.java:17)
```
`Application.java:17` is the line `FusekiServer fusekiServer = FusekiServer.create()`, see below.

This is the code:

```java
@SpringBootApplication
public class Application {
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
		Dataset ds = DatasetFactory.createTxnMem();
		FusekiServer fusekiServer = FusekiServer.create()
				.add("/", ds)
				.build();
		fusekiServer.start();
	}
}
```

And this is the `build.gradle`:

```gradle
plugins {
	id "java"
	id "org.springframework.boot" version "3.0.0"
	id "io.spring.dependency-management" version "1.1.0"
}
sourceCompatibility = "17"
repositories {
	mavenCentral()
}
dependencies {
	implementation "org.springframework.boot:spring-boot-starter-web"
	implementation "org.apache.jena:jena-fuseki-main:4.7.0"
}
```

### Are you interested in making a pull request?

Maybe

**Comment by kinow** [comment] 2023-03-11 20:29
I believe this is a known issue, #1763

**Comment by afs** [comment] 2023-03-13 10:01
It is possible to convert binary jars from Jakarta 8 (where JavaEE servlet and other package are under `javax`) to Jakarta 9 (using `jakarta` packages). There are some tools around (e.g. from Tomcat) to do this. At their core, they are shading the jars to do a rename, with caution because not all `javax` packages are part of JavaEE and remain as `javax`.

That also means the reverse direction should also work to go from `jakarta` to `javax`.

See also:
https://lists.apache.org/thread/3pjkdtoqbz30p8nbz8p59c6jcy1b2gpq

**Comment by afs** [comment] 2023-07-01 21:16
Duplicate of #1763

**Closed by afs** 2023-07-01 21:16 UTC
Labels: bug
