### ISSUE TITLE
Open iterators when cancelling queries

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#2881] opened 2024-12-06 21:24 UTC
### Version

5.3.0-SNAPSHOT

### What happened?

Sometimes when cancelling queries warnings are logged such as:
```
Open iterator: QueryIterPeek/123
Open iterator: QueryIterSingleton/456
```

So far I noticed this to happen when BGPs and UNIONs are involved, but this may not be exhaustive.

It turns out that not all the iterator construction in ARQ is performed truly lazy, which causes some parts of the code to leave iterators open if an exception happens during the iterator construction.

After investigation it seems that the warnings should (usually) be harmless, because the `QueryIter`s are tracked in the `ExecutionContext` and thus eventually become closed without leaking resources.

However, seeing these warnings suggests that resources *might* be leaked - so this is an issue that IMO should be fixed.

See the PR for a test case and the proposed fixes.

### Are you interested in making a pull request?

Yes

**Comment by afs** [comment] 2024-12-07 08:45
I took the test case from the PR and have run it multiple times and not got any test failures.

**Comment by Aklakan** [comment] 2024-12-07 09:12
The test case is not failing - but it produces warnings non-deterministically:
![Screenshot from 2024-12-07 10-09-42](https://github.com/user-attachments/assets/d633c222-0cd4-47f0-b3af-574db1429b50)

**Comment by Aklakan** [comment] 2024-12-07 09:48
> One thing to consider is invert the responsibilities have specific management of external resources - for example, add to a specific manager, one per query execution, pass in the context. End of execution clears up. This would also be good for per-execution caches.

Maybe I am misunderstanding, how would that differ from the current design?
Currently:
1. QueryIter registers itself at the execution context - the resource manager.
2. Something fails midway, resources are still tracked in the resource manager (although they could have been closed earlier).
3. End of execution closes all tracked resources - but warns because this shouldn't normally happen.

**Comment by afs** [comment] 2024-12-07 11:02
The current design does not have a way to track item that must have clear-up applied. The resource manager would a new thing - not based on the close iterator mechanism. It is only things that need clear-up that need to be handled carefully. The GC will deal with the rest. 

If there are declared resources, we don't have to put in code for less-common situations on the performance path and we don't have to code in one place (general execution) so connected to code in another place (spacial resources).

**Comment by afs** [comment] 2024-12-07 11:06
I don't get warnings.

Tests that pass-don't-pass are difficult to handle in the overall build. It really is error prone to rely on spotting warnings in a maven build. I've been trying to fix the current ones which (I hope) are spurious cases where the test code is by design hitting a warning case.

**Comment by Aklakan** [comment] 2024-12-07 12:03
I updated the code to your comments and added an `OpenIteratorException` that should now cause the test to fail.

> How many times do they need to be run?

The system I am working on has 6+7 physical and 6+(7*2)=20 virtual cores. The longest streak without warnings was maybe 10 times. Usually I get it roughly every 3 to 5 runs.

**Closed** 2024-12-27 18:25 UTC
Labels: bug
