### ISSUE TITLE
ResultSetFactory don't close the InputStream.

### ISSUE THREAD

**Issue by wangxj3** [apache/jena#2309] opened 2024-03-05 09:22 UTC
### Version

mian

### What happened?

ResultSetFactory don't close the InputStream. In the line of 69,function of load(String filenameOrURI, ResultsFormat format)

### Are you interested in making a pull request?

None

**Comment by rvesse** [comment] 2024-03-05 09:59
Not a bug, this is by design. It allows for Jena to stream process the results which minimises memory overheads

Consumers of the ResultSet API are required to ensure they `close()` it appropriately which will close the underlying `InputStream` (or other resources) where appropriate

**Comment by afs** [comment] 2024-03-05 22:52
If an InputStream is passed in, then the responsibility for closing is the caller, which fits the try-with-resources pattern.

In the case of `load(String filenameOrURI, ResultsFormat format)`, the `InputStream` is created within `ResultSetFactory` and should be used with try-with-resources.

**Closed** 2024-03-07 21:06 UTC
Labels: bug
