### ISSUE TITLE
jena-serviceenhancer NoClassDefFoundError

### ISSUE THREAD

**Issue by royassis** [apache/jena#2288] opened 2024-02-25 09:15 UTC
### Version

5.0.0-rc1

### What happened?

I am trying to add the server enhancer plugin to fuseki server as described here:  
https://jena.apache.org/documentation/query/service_enhancer.html

I downloaded the .jar file from here:  
https://mvnrepository.com/artifact/org.apache.jena/jena-serviceenhancer/5.0.0-rc1

And placed it in `/home/ubuntu/apache/apache-jena-fuseki-5.0.0-rc1/run/extra`.

Getting the error attached below:

### Relevant output and stacktrace

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
        at org.apache.jena.sparql.service.enhancer.impl.ServiceResponseCache.<init>(ServiceResponseCache.java:59)
        at org.apache.jena.sparql.service.enhancer.impl.ServiceResponseCache.<init>(ServiceResponseCache.java:53)
        at org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerInit.init(ServiceEnhancerInit.java:90)
        at org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerInit.start(ServiceEnhancerInit.java:81)
        at org.apache.jena.base.module.Subsystem.lambda$initialize$1(Subsystem.java:117)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
        at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
        at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
        at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:89)
        at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:29)
        at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:65)
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        ... 12 more
```
```


### Are you interested in making a pull request?

No

**Comment by royassis** [comment] 2024-02-25 09:18
Downloading the Gauava .jre from here:  
https://mvnrepository.com/artifact/com.google.guava/guava/33.0.0-jre

And placing it in run/extra resolved the issue.

**Comment by namedgraph** [comment] 2024-02-25 09:57
Duplicate of #2161 ?

**Comment by Aklakan** [comment] 2024-02-27 14:46
Also related: https://github.com/apache/jena/issues/2271

Will update the documentation this week as this is the second issue in quite a short while.

**Comment by Aklakan** [comment] 2024-03-20 12:26
Took a bit longer than anticipated, but the documentation update happened: https://github.com/apache/jena-site/pull/182

**Comment by afs** [comment] 2024-03-21 13:41
> the documentation update is in progress:

https://github.com/apache/jena-site/pull/182 is merged

@Aklakan  Is this issues finished now?

**Closed** 2024-03-21 14:30 UTC
Labels: bug

**Comment by afs** [comment] 2024-03-21 16:31
Thanks!
